install:
	npm install

test:
	node_modules/react-scripts/bin/react-scripts.js test --env=jsdom

start:
	PORT=3006 node_modules/react-scripts/bin/react-scripts.js start

build:
	node_modules/react-scripts/bin/react-scripts.js build

eject:
	node_modules/react-scripts/bin/react-scripts.js eject
