install:
	npm install

test-unit:
	./node_modules/.bin/mocha './src/**/*.js'

test: test-unit

start:
	node_modules/react-scripts/bin/react-scripts.js start

build:
	node_modules/react-scripts/bin/react-scripts.js build

eject:
	node_modules/react-scripts/bin/react-scripts.js eject
